---
  
- hosts: all
  become: true
  tasks:
  - name: update apt index
    apt:
      update_cache: yes 
  
  - name: remove apache2
    apt:
      name: apache2
      state: absent

  - name: remove php support
    apt: 
      name: libapache2-mod-php
      state: absent
